-- =====================================================
-- EDUTAILOR - COMPLETE DATABASE SCHEMA
-- PostgreSQL 15+
-- Includes all changes for Updates 1-8
-- Run this file ONCE on a fresh edutailor database
-- WARNING: Drops all existing tables and data
-- =====================================================

-- Drop existing tables in correct order
DROP TABLE IF EXISTS question_performance CASCADE;
DROP TABLE IF EXISTS quiz_attempts CASCADE;
DROP TABLE IF EXISTS student_questions CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS content_generation_log CASCADE;
DROP TABLE IF EXISTS content_status CASCADE;
DROP TABLE IF EXISTS student_progress CASCADE;
DROP TABLE IF EXISTS user_preferences CASCADE;
DROP TABLE IF EXISTS vark_assessments CASCADE;
DROP TABLE IF EXISTS format_tracking CASCADE;
DROP TABLE IF EXISTS lecture_slides CASCADE;
DROP TABLE IF EXISTS otp_verifications CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS chapters CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- =====================================================
-- 1. USERS TABLE
-- Update 2: Added is_verified, profile_picture_url
-- =====================================================
CREATE TABLE users (
    id                  SERIAL PRIMARY KEY,
    email               VARCHAR(255) UNIQUE NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    full_name           VARCHAR(255) NOT NULL,
    role                VARCHAR(50) NOT NULL CHECK (role IN ('student', 'teacher')),
    is_verified         BOOLEAN DEFAULT FALSE,
    profile_picture_url VARCHAR(500),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login          TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

-- =====================================================
-- 2. OTP VERIFICATIONS TABLE
-- Update 6: Email verification and password reset
-- =====================================================
CREATE TABLE otp_verifications (
    id          SERIAL PRIMARY KEY,
    user_id     INTEGER REFERENCES users(id) ON DELETE CASCADE,
    email       VARCHAR(255) NOT NULL,
    otp_code    VARCHAR(6) NOT NULL,
    otp_type    VARCHAR(30) NOT NULL CHECK (otp_type IN ('email_verification', 'password_reset')),
    expires_at  TIMESTAMP NOT NULL,
    used        BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_otp_user ON otp_verifications(user_id);
CREATE INDEX idx_otp_email ON otp_verifications(email);
CREATE INDEX idx_otp_type ON otp_verifications(otp_type);

-- =====================================================
-- 3. VARK ASSESSMENTS TABLE
-- =====================================================
CREATE TABLE vark_assessments (
    id                  SERIAL PRIMARY KEY,
    user_id             INTEGER REFERENCES users(id) ON DELETE CASCADE,
    visual_score        INTEGER NOT NULL,
    auditory_score      INTEGER NOT NULL,
    reading_score       INTEGER NOT NULL,
    kinesthetic_score   INTEGER NOT NULL,
    recommended_format  VARCHAR(50) NOT NULL,
    assessed_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vark_user ON vark_assessments(user_id);

-- =====================================================
-- 4. USER PREFERENCES TABLE
-- =====================================================
CREATE TABLE user_preferences (
    user_id             INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    current_format      VARCHAR(50),
    recommended_format  VARCHAR(50),
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 5. CHAPTERS TABLE
-- =====================================================
CREATE TABLE chapters (
    id              SERIAL PRIMARY KEY,
    chapter_number  INTEGER NOT NULL UNIQUE,
    title           VARCHAR(255) NOT NULL,
    description     TEXT
);

-- =====================================================
-- 6. TOPICS TABLE
-- Update 2: Removed visual_explanation
-- Update 2: Added visual_narration
-- Update 8: Added mindmap_json
-- =====================================================
CREATE TABLE topics (
    topic_id        VARCHAR(10) PRIMARY KEY,
    chapter_id      INTEGER REFERENCES chapters(id),
    topic_name      VARCHAR(255) NOT NULL,

    -- English Text Content
    paragraph_1     TEXT NOT NULL,
    paragraph_2     TEXT NOT NULL,
    paragraph_3     TEXT,
    paragraph_4     TEXT,
    paragraph_5     TEXT,

    -- Visual
    visual_type     VARCHAR(20) CHECK (visual_type IN ('animation', 'diagram')),
    visual_path     VARCHAR(500),

    -- Update 3: Visual narration (generated by Claude API, one-time)
    visual_narration TEXT,

    -- Urdu Translation (generated by Groq)
    urdu_paragraph_1 TEXT,
    urdu_paragraph_2 TEXT,
    urdu_paragraph_3 TEXT,
    urdu_paragraph_4 TEXT,
    urdu_paragraph_5 TEXT,

    -- Audio
    audio_en_path   VARCHAR(500),

    -- Update 8: Mindmap JSON (generated by Claude API, one-time)
    mindmap_json    JSONB,

    -- Metadata
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_topics_chapter ON topics(chapter_id);

-- =====================================================
-- 7. LECTURE SLIDES TABLE
-- Update 8: Lecture tab feature
-- =====================================================
CREATE TABLE lecture_slides (
    id              SERIAL PRIMARY KEY,
    topic_id        VARCHAR(10) NOT NULL REFERENCES topics(topic_id) ON DELETE CASCADE,
    slide_number    INTEGER NOT NULL,
    title           VARCHAR(255) NOT NULL,
    bullets         JSONB NOT NULL,
    narration_ur    TEXT,
    audio_ur_path   VARCHAR(500),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(topic_id, slide_number)
);

CREATE INDEX idx_lecture_slides_topic ON lecture_slides(topic_id);

-- =====================================================
-- 8. CONTENT STATUS TABLE
-- =====================================================
CREATE TABLE content_status (
    id              SERIAL PRIMARY KEY,
    topic_id        VARCHAR(10) REFERENCES topics(topic_id),
    content_type    VARCHAR(50) NOT NULL,
    -- Values: 'urdu', 'audio_en', 'animation', 'diagram',
    --         'visual_narration', 'lecture', 'mindmap'
    status          VARCHAR(50) NOT NULL,
    -- Values: 'pending', 'generated', 'approved', 'rejected'
    file_path       VARCHAR(500),
    generated_at    TIMESTAMP,
    approved_by     INTEGER REFERENCES users(id),
    approved_at     TIMESTAMP,
    UNIQUE(topic_id, content_type)
);

CREATE INDEX idx_content_status_topic ON content_status(topic_id);
CREATE INDEX idx_content_status_status ON content_status(status);

-- =====================================================
-- 9. STUDENT PROGRESS TABLE
-- =====================================================
CREATE TABLE student_progress (
    user_id             INTEGER REFERENCES users(id) ON DELETE CASCADE,
    topic_id            VARCHAR(10) REFERENCES topics(topic_id),
    status              VARCHAR(50) NOT NULL DEFAULT 'not_started',
    -- Values: 'not_started', 'in_progress', 'completed'
    best_score          INTEGER,
    attempts_count      INTEGER DEFAULT 0,
    time_spent_seconds  INTEGER DEFAULT 0,
    last_accessed       TIMESTAMP,
    completed_at        TIMESTAMP,
    PRIMARY KEY (user_id, topic_id)
);

CREATE INDEX idx_progress_user ON student_progress(user_id);
CREATE INDEX idx_progress_status ON student_progress(status);

-- =====================================================
-- 10. FORMAT TRACKING TABLE
-- Update 2: Included in schema
-- =====================================================
CREATE TABLE format_tracking (
    id                  SERIAL PRIMARY KEY,
    user_id             INTEGER REFERENCES users(id) ON DELETE CASCADE,
    topic_id            VARCHAR(10) REFERENCES topics(topic_id),
    format              VARCHAR(20) NOT NULL CHECK (format IN ('english', 'urdu', 'audio_en', 'visual', 'lecture')),
    time_spent_seconds  INTEGER DEFAULT 0,
    session_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quiz_score_after    INTEGER
);

CREATE INDEX idx_format_tracking_user ON format_tracking(user_id);
CREATE INDEX idx_format_tracking_topic ON format_tracking(topic_id);
CREATE INDEX idx_format_tracking_format ON format_tracking(format);

-- =====================================================
-- 11. QUIZ ATTEMPTS TABLE
-- =====================================================
CREATE TABLE quiz_attempts (
    id                          SERIAL PRIMARY KEY,
    user_id                     INTEGER REFERENCES users(id) ON DELETE CASCADE,
    topic_id                    VARCHAR(10) REFERENCES topics(topic_id),
    format_used                 VARCHAR(50) NOT NULL,
    mcq_score                   INTEGER NOT NULL,
    subjective_score            INTEGER NOT NULL,
    total_score                 INTEGER NOT NULL,
    mcq_responses               JSONB,
    subjective_responses        JSONB,
    time_spent_learning_seconds INTEGER,
    quiz_duration_seconds       INTEGER,
    attempted_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_quiz_user ON quiz_attempts(user_id);
CREATE INDEX idx_quiz_topic ON quiz_attempts(topic_id);
CREATE INDEX idx_quiz_format ON quiz_attempts(format_used);
CREATE INDEX idx_quiz_attempted ON quiz_attempts(attempted_at);

-- =====================================================
-- 12. QUESTION PERFORMANCE TABLE
-- =====================================================
CREATE TABLE question_performance (
    id                  SERIAL PRIMARY KEY,
    quiz_attempt_id     INTEGER REFERENCES quiz_attempts(id) ON DELETE CASCADE,
    user_id             INTEGER REFERENCES users(id) ON DELETE CASCADE,
    topic_id            VARCHAR(10) REFERENCES topics(topic_id),
    question_type       VARCHAR(20),
    question_text       TEXT,
    student_answer      TEXT,
    correct_answer      TEXT,
    reference_answer    TEXT,
    is_correct          BOOLEAN,
    similarity_score    FLOAT,
    points_earned       INTEGER,
    points_possible     INTEGER,
    answered_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_question_perf_topic ON question_performance(topic_id);
CREATE INDEX idx_question_perf_type ON question_performance(question_type);

-- =====================================================
-- 13. STUDENT QUESTIONS TABLE
-- =====================================================
CREATE TABLE student_questions (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE CASCADE,
    topic_id        VARCHAR(10) REFERENCES topics(topic_id),
    question_text   TEXT NOT NULL,
    answer_text     TEXT,
    citation        VARCHAR(500),
    was_helpful     BOOLEAN,
    asked_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_questions_user ON student_questions(user_id);
CREATE INDEX idx_questions_topic ON student_questions(topic_id);

-- =====================================================
-- 14. FEEDBACK TABLE
-- =====================================================
CREATE TABLE feedback (
    id              SERIAL PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE CASCADE,
    topic_id        VARCHAR(10) REFERENCES topics(topic_id),
    rating          INTEGER CHECK (rating >= 1 AND rating <= 5),
    feedback_text   TEXT,
    submitted_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_feedback_topic ON feedback(topic_id);
CREATE INDEX idx_feedback_rating ON feedback(rating);

-- =====================================================
-- 15. CONTENT GENERATION LOG TABLE
-- =====================================================
CREATE TABLE content_generation_log (
    id              SERIAL PRIMARY KEY,
    topic_id        VARCHAR(10) REFERENCES topics(topic_id),
    content_type    VARCHAR(50) NOT NULL,
    generated_code  TEXT,
    preview_path    VARCHAR(500),
    status          VARCHAR(50) NOT NULL,
    generated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_gen_log_topic ON content_generation_log(topic_id);

-- =====================================================
-- 16. INSERT CHAPTERS (All 5)
-- =====================================================
INSERT INTO chapters (chapter_number, title, description) VALUES
(1, 'Chemical Bonding',      'Understanding how atoms form bonds and the different types of chemical bonds'),
(2, 'Atomic Structure',      'The structure of atoms, subatomic particles, isotopes, and electronic configuration'),
(3, 'States of Matter',      'Properties of solids, liquids and gases, changes of state, diffusion, and gas laws'),
(4, 'Chemical Reactions',    'Types of reactions, energy changes, reaction rates, redox, electrolysis, and equilibrium'),
(5, 'Acids, Bases and Salts','Properties of acids and bases, the pH scale, neutralization, and preparation of salts');

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
-- Run after executing this file to verify:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;
-- SELECT * FROM chapters;
-- SELECT COUNT(*) FROM topics;

-- =====================================================
-- SCHEMA CREATION COMPLETE
-- Next step: Run insert_chemistry_content.sql
-- =====================================================