-- =====================================================
-- EDUTAILOR - INSERT CHEMISTRY CONTENT
-- All 27 topics across 5 chapters
-- Run AFTER create_database_schema.sql
-- NOTE: visual_narration and mindmap_json are NULL here
--       They are generated later by teacher via Claude API
-- =====================================================

-- =====================================================
-- CHAPTER 1: CHEMICAL BONDING (6 topics: 1.1 - 1.6)
-- =====================================================

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'1.1', 1, 'Ionic Bonding', 'animation',
'An ionic bond is a type of chemical bond formed through the electrostatic attraction between oppositely charged ions. This type of bonding occurs when electrons are transferred from one atom to another, typically from a metal to a non-metal. The metal atom loses electrons to become a positively charged cation, while the non-metal gains these electrons to become a negatively charged anion. The resulting electrostatic force of attraction between these oppositely charged ions holds them together in an ionic compound.',
'The formation of ionic bonds typically occurs between metals and non-metals due to their difference in electronegativity. Metals such as sodium have low ionization energies and readily lose their valence electrons to achieve a stable electron configuration. Non-metals such as chlorine have high electron affinities and readily gain electrons to complete their outer shell, typically achieving a noble gas configuration. For example, when sodium with one valence electron reacts with chlorine with seven valence electrons, sodium loses one electron to become Na⁺ and chlorine gains one electron to become Cl⁻, both achieving stable octets.',
'Ionic compounds possess distinctive physical and chemical properties that stem from their ionic bonding. They typically have high melting and boiling points due to the strong electrostatic forces between ions, which require significant energy to overcome. In their solid state, ionic compounds do not conduct electricity because the ions are fixed in position within the crystal lattice. However, when dissolved in water or melted, the ions become mobile and can conduct electricity. Common examples of ionic compounds include sodium chloride NaCl, magnesium oxide MgO, and calcium chloride CaCl₂.',
'The crystal lattice structure of ionic compounds is another important characteristic. Ions arrange themselves in a regular, repeating three-dimensional pattern to maximize attractive forces and minimize repulsive forces between ions. This arrangement creates a strong, rigid structure. The lattice energy, which is the energy required to separate one mole of an ionic solid into gaseous ions, is a measure of the strength of the ionic bonds. Compounds with smaller ions and higher charges generally have greater lattice energies and consequently higher melting points.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'1.2', 1, 'Covalent Bonding', 'animation',
'A covalent bond is a chemical bond formed when two atoms share one or more pairs of electrons. Unlike ionic bonding where electrons are transferred, covalent bonding involves the mutual sharing of electrons between atoms. This type of bonding typically occurs between non-metal atoms that have similar electronegativities. The shared electrons are attracted to the nuclei of both atoms, creating a strong bond that holds the atoms together. The shared pair of electrons is called a bonding pair, while electrons that are not shared are called lone pairs or non-bonding pairs.',
'Covalent bonds can be single, double, or triple depending on the number of electron pairs shared between atoms. A single covalent bond involves the sharing of one pair of electrons, as seen in hydrogen gas H₂ where each hydrogen atom contributes one electron. A double covalent bond involves the sharing of two pairs of electrons, such as in oxygen gas O₂. A triple covalent bond involves the sharing of three pairs of electrons, as in nitrogen gas N₂. Generally, as the number of shared electron pairs increases, the bond becomes shorter and stronger, requiring more energy to break.',
'The properties of covalent compounds differ significantly from those of ionic compounds. Covalent compounds typically have lower melting and boiling points because the intermolecular forces between molecules are weaker than the ionic bonds in ionic compounds. Most covalent compounds do not conduct electricity, even when dissolved in water, because they do not form ions. Many covalent compounds are soluble in non-polar solvents but insoluble in water. Common examples include water H₂O, methane CH₄, carbon dioxide CO₂, and ammonia NH₃.',
'The concept of molecular geometry is important in understanding covalent compounds. The arrangement of atoms in a molecule affects its physical and chemical properties. For instance, the bent shape of water molecules contributes to water''s unique properties, while the tetrahedral arrangement of carbon in methane influences its reactivity. Lewis structures are often used to represent covalent bonding, showing all valence electrons as dots and bonding pairs as lines between atoms. These diagrams help predict molecular shapes and understand chemical behavior.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3) VALUES (
'1.3', 1, 'Metallic Bonding', 'animation',
'Metallic bonding is the type of chemical bonding that holds metal atoms together in a solid metal. In a metal, each atom releases its outermost valence electrons, which are then free to move throughout the entire metallic structure. This creates a lattice of positively charged metal ions surrounded by a sea or cloud of delocalized electrons that do not belong to any particular atom. The metallic bond is the strong electrostatic attraction between the positive metal ions and the surrounding sea of delocalized electrons.',
'The presence of delocalized electrons directly explains the excellent electrical and thermal conductivity of metals. When a voltage is applied across a metal, the free electrons can move throughout the structure in a single direction, constituting an electric current. Similarly, when one part of a metal is heated, the mobile electrons rapidly transfer kinetic energy to other parts of the structure, explaining why metals are good thermal conductors. The strength of the metallic bond depends on the number of delocalized electrons per atom and the charge density of the metal ions.',
'The unique mechanical properties of metals including malleability and ductility are also explained by the metallic bonding model. Metals can be hammered into sheets which is malleability or drawn into wires which is ductility because the layers of metal ions can slide past one another without breaking the metallic bond. As one layer moves relative to another, the delocalized electrons simply rearrange to maintain the bonding between the new arrangement of ions. This is in sharp contrast to ionic compounds, where attempting to deform the lattice brings like-charged ions close together, causing repulsion and fracture.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3) VALUES (
'1.4', 1, 'Polar Covalent Bonds', 'animation',
'A polar covalent bond is a type of covalent bond in which electrons are shared unequally between two atoms. This unequal sharing occurs when the two atoms have different electronegativities — one atom attracts the shared electrons more strongly than the other. Electronegativity is the ability of an atom to attract bonding electrons toward itself. When the electronegativity difference between two atoms is moderate, typically between 0.4 and 1.7 on the Pauling scale, a polar covalent bond forms. The atom with higher electronegativity develops a partial negative charge denoted delta minus, while the atom with lower electronegativity develops a partial positive charge denoted delta plus.',
'The polarity of a bond has significant effects on the properties of molecules. In a molecule like hydrogen chloride HCl, chlorine is more electronegative than hydrogen, so the bonding electrons spend more time near the chlorine atom. This creates a dipole moment which is a measure of the separation of positive and negative charges. Dipole moments are represented by arrows pointing from the positive end to the negative end of the bond. The presence of polar bonds can make entire molecules polar if the bond dipoles do not cancel out due to molecular geometry. For example, water H₂O is a polar molecule because it has polar O-H bonds arranged in a bent shape, resulting in a net dipole moment.',
'Polar covalent bonds play a crucial role in determining molecular behavior and interactions. Molecules with polar bonds often have higher boiling points than non-polar molecules of similar size because the partial charges allow for stronger intermolecular forces, specifically dipole-dipole interactions. Polar molecules tend to dissolve well in polar solvents like water, following the principle that like dissolves like. Understanding bond polarity is essential in organic chemistry, biochemistry, and materials science, as it affects everything from protein folding to the properties of polymers. Common examples of molecules with polar covalent bonds include water H₂O, ammonia NH₃, and hydrogen fluoride HF.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3) VALUES (
'1.5', 1, 'Hydrogen Bonding', 'diagram',
'A hydrogen bond is a special type of intermolecular force that occurs when a hydrogen atom bonded to a highly electronegative atom such as nitrogen, oxygen, or fluorine is attracted to another electronegative atom in a nearby molecule. Despite its name, a hydrogen bond is not a true chemical bond like ionic or covalent bonds, but rather a strong dipole-dipole attraction. The hydrogen atom, being small and having its electron pulled toward the electronegative atom it is bonded to, develops a significant partial positive charge. This partially positive hydrogen is then attracted to the lone pair of electrons on a nearby electronegative atom, creating the hydrogen bond.',
'Hydrogen bonding is responsible for many unique and important properties of substances, particularly water. Water''s unusually high boiling point for such a small molecule is due to extensive hydrogen bonding between water molecules. Each water molecule can form up to four hydrogen bonds — two through its hydrogen atoms and two through the lone pairs on its oxygen atom. This network of hydrogen bonds also explains why ice is less dense than liquid water. When water freezes, hydrogen bonds arrange the molecules in a hexagonal lattice with more space between molecules than in the liquid state, causing ice to float. This property is crucial for aquatic life, as it prevents bodies of water from freezing solid from the bottom up.',
'Hydrogen bonding plays a vital role in biological systems. The structure and function of proteins and nucleic acids depend heavily on hydrogen bonds. In DNA, hydrogen bonds between complementary base pairs hold the two strands of the double helix together. These bonds are strong enough to maintain the DNA structure but weak enough to allow the strands to separate during replication and transcription. In proteins, hydrogen bonds help stabilize secondary structures like alpha helices and beta sheets. Although hydrogen bonds are weaker than covalent or ionic bonds, typically about 5 percent the strength of a covalent bond, they are significantly stronger than other intermolecular forces.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'1.6', 1, 'Bond Energy and Bond Length', 'animation',
'Bond energy, also called bond enthalpy, is the amount of energy required to break one mole of a particular type of bond in gaseous molecules. It is a measure of bond strength — the stronger the bond, the more energy is required to break it. Bond energy is always a positive value because breaking bonds requires energy input, making it an endothermic process. Conversely, when bonds form, energy is released in an exothermic process. Different types of bonds have different bond energies. For example, the C-H bond in methane has a bond energy of approximately 413 kJ/mol, while the C-C bond has about 348 kJ/mol.',
'Bond length is the average distance between the nuclei of two bonded atoms. It is determined by a balance between attractive and repulsive forces — the nuclei and electrons attract each other, but the nuclei repel each other as do the electrons. Bond length is typically measured in picometers or angstroms. There is an important inverse relationship between bond energy and bond length — shorter bonds are generally stronger and have higher bond energies, while longer bonds are weaker with lower bond energies. This relationship exists because in shorter bonds, the bonding electrons are held more tightly between the nuclei, creating a stronger electrostatic attraction.',
'The relationship between bond order, bond length, and bond energy can be observed in molecules with single, double, and triple bonds. Consider carbon-carbon bonds: a C-C single bond has a length of about 154 pm and bond energy of 348 kJ/mol; a C=C double bond is shorter at 134 pm and stronger at 614 kJ/mol; and a C≡C triple bond is even shorter at 120 pm and strongest at 839 kJ/mol. This trend occurs because as more electron pairs are shared between atoms, the bond becomes shorter and stronger. These relationships are fundamental to understanding chemical reactivity, as bonds with lower bond energies are generally easier to break and therefore more reactive.',
'Bond energy and bond length data have practical applications in chemistry. They can be used to estimate the enthalpy change of reactions by calculating the difference between energy required to break bonds in reactants and energy released when forming bonds in products. This is particularly useful for reactions where direct measurement is difficult. Additionally, comparing bond energies helps explain why certain reactions occur more readily than others. For instance, the high bond energy of the N≡N triple bond in nitrogen gas explains why nitrogen is relatively unreactive under normal conditions, despite being abundant in the atmosphere.'
);

-- =====================================================
-- CHAPTER 2: ATOMIC STRUCTURE (5 topics: 2.1 - 2.5)
-- =====================================================

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'2.1', 2, 'Structure of the Atom', 'animation',
'An atom is the smallest unit of an element that retains the chemical properties of that element. Every atom consists of two main regions: a tiny, dense nucleus at the center and an electron cloud surrounding it. The nucleus contains protons, which carry a positive charge, and neutrons, which have no charge. Electrons, which carry a negative charge, occupy the space outside the nucleus in regions called electron shells or energy levels. The number of protons in the nucleus determines what element the atom is, and this number is called the atomic number.',
'The three subatomic particles have very different masses and charges. A proton has a relative mass of 1 and a relative charge of plus one. A neutron also has a relative mass of 1 but carries no charge, giving it a relative charge of zero. An electron has a negligible mass approximately 1/1836 of a proton and carries a relative charge of minus one. In a neutral atom, the number of protons always equals the number of electrons, which is why atoms have no overall charge. The mass number of an atom is the total number of protons and neutrons in the nucleus.',
'Electrons are arranged in shells around the nucleus, and each shell can hold a maximum number of electrons. The first shell closest to the nucleus can hold a maximum of 2 electrons. The second shell can hold a maximum of 8 electrons. The third shell can also hold up to 8 electrons in elements relevant to O-Level chemistry. This arrangement is called the electronic configuration and is written as a series of numbers showing electrons in each shell. For example, sodium with atomic number 11 has the electronic configuration 2,8,1 meaning 2 electrons in the first shell, 8 in the second, and 1 in the third.',
'The electronic configuration of an atom determines its chemical properties, particularly its reactivity. Atoms with completely filled outer shells, like the noble gases, are very stable and unreactive. Atoms with nearly full or nearly empty outer shells tend to be highly reactive, as they can achieve stability by gaining, losing, or sharing electrons. The outermost electrons are called valence electrons, and it is these electrons that participate in chemical bonding. Understanding the arrangement of electrons is therefore fundamental to understanding why and how elements react with each other.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'2.2', 2, 'Isotopes', 'diagram',
'Isotopes are atoms of the same element that have the same number of protons but different numbers of neutrons in their nuclei. Because they have the same number of protons, isotopes of an element have the same atomic number and the same chemical properties. However, because they have different numbers of neutrons, they have different mass numbers and therefore different masses. The term isotope comes from the Greek words meaning equal place, referring to the fact that isotopes occupy the same position in the periodic table.',
'Carbon provides a well-known example of isotopes. Carbon-12 has 6 protons and 6 neutrons, giving it a mass number of 12. Carbon-13 has 6 protons and 7 neutrons, giving it a mass number of 13. Carbon-14 has 6 protons and 8 neutrons, giving it a mass number of 14. All three are carbon because they all have 6 protons. Another important example is hydrogen, which has three isotopes: ordinary hydrogen called protium with 1 proton and 0 neutrons, deuterium with 1 proton and 1 neutron, and tritium with 1 proton and 2 neutrons.',
'The relative atomic mass of an element takes into account the existence of isotopes. It is the weighted average mass of all naturally occurring isotopes of an element relative to one-twelfth the mass of a carbon-12 atom. For example, chlorine has two main isotopes: chlorine-35 which makes up about 75 percent of natural chlorine and chlorine-37 which makes up about 25 percent. The relative atomic mass of chlorine is therefore approximately 35.5, which is the weighted average of these two isotopes. This explains why the relative atomic masses of many elements are not whole numbers.',
'Some isotopes are radioactive, meaning their nuclei are unstable and spontaneously decay, emitting radiation in the process. These are called radioisotopes or radioactive isotopes. Carbon-14 is a well-known radioisotope used in radiocarbon dating to determine the age of ancient organic materials. Uranium-235 and uranium-238 are radioisotopes used in nuclear energy production. In medicine, technetium-99m is widely used as a radioactive tracer in medical imaging. The stability of an isotope depends on the ratio of neutrons to protons in the nucleus — too many or too few neutrons relative to protons leads to instability.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'2.3', 2, 'Electronic Configuration', 'animation',
'Electronic configuration describes the arrangement of electrons in the shells or energy levels of an atom. Electrons occupy shells in order of increasing energy, filling the innermost shell first before moving to the next. The first shell can hold a maximum of 2 electrons, the second shell can hold up to 8 electrons, and the third shell can hold up to 8 electrons for elements in the first three periods of the periodic table. This filling pattern follows specific rules and determines the chemical behavior of each element.',
'The electronic configurations of the first twenty elements follow a clear pattern. Hydrogen has 1 electron giving configuration 1. Helium has 2 electrons giving configuration 2. Lithium has 3 electrons giving configuration 2,1. Neon has 10 electrons giving configuration 2,8. Sodium has 11 electrons giving configuration 2,8,1. Argon has 18 electrons giving configuration 2,8,8. Calcium has 20 electrons giving configuration 2,8,8,2. Elements in the same group of the periodic table have the same number of valence electrons and therefore similar chemical properties.',
'The relationship between electronic configuration and the periodic table is fundamental. The period number of an element corresponds to the number of electron shells it has. Group 1 elements all have one electron in their outermost shell, group 2 elements have two, and so on across the table. Group 0 or Group 18 elements, the noble gases, have completely filled outer shells which explains their chemical inertness. The number of valence electrons determines how an element will react — whether it will lose electrons like metals, gain electrons like non-metals, or share electrons in covalent bonding.',
'Electronic configuration is directly related to the formation of ions. When a metal atom loses electrons to form a positive ion, it loses electrons from its outermost shell. For example, sodium 2,8,1 loses one electron to form Na⁺ with configuration 2,8, which is the same as neon. When a non-metal atom gains electrons to form a negative ion, the electrons are added to the outermost shell. For example, chlorine 2,8,7 gains one electron to form Cl⁻ with configuration 2,8,8, which is the same as argon. This tendency to achieve noble gas configuration drives much of chemical reactivity.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'2.4', 2, 'Proton Number and Nucleon Number', 'diagram',
'The proton number, also called the atomic number, is the number of protons in the nucleus of an atom. It is represented by the symbol Z. The proton number uniquely identifies an element — every atom of the same element has the same number of protons. For example, all carbon atoms have 6 protons, all oxygen atoms have 8 protons, and all iron atoms have 26 protons. If the proton number changes, the atom becomes a different element entirely. The proton number also equals the number of electrons in a neutral atom.',
'The nucleon number, also called the mass number, is the total number of protons and neutrons in the nucleus of an atom. It is represented by the symbol A. Nucleons are the particles found in the nucleus — both protons and neutrons are nucleons. The number of neutrons in an atom can be calculated by subtracting the proton number from the nucleon number: neutrons equals A minus Z. For example, an atom of sodium has a proton number of 11 and a nucleon number of 23, so it has 23 minus 11 equals 12 neutrons.',
'Atoms are represented using a standard notation that shows both the proton number and nucleon number. In this notation, the chemical symbol of the element is written with the nucleon number as a superscript on the upper left and the proton number as a subscript on the lower left. For example, carbon-12 is written with 12 as the superscript and 6 as the subscript before the symbol C. This notation provides complete information about the composition of an atom''s nucleus, allowing the number of protons, neutrons, and electrons to be determined immediately.',
'Understanding proton number and nucleon number is essential for working with isotopes and nuclear reactions. When writing equations for nuclear reactions, the total proton numbers and nucleon numbers must be balanced on both sides of the equation, similar to how atoms are balanced in chemical equations. The proton number determines an element''s position in the periodic table — elements are arranged in order of increasing proton number. The discovery that elements are characterized by their proton number, rather than their mass, was one of the most important developments in the history of chemistry and physics.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'2.5', 2, 'Periodic Table and Electron Shells', 'diagram',
'The modern periodic table arranges all known elements in order of increasing atomic number, organized into rows called periods and columns called groups. There are currently 118 confirmed elements in the periodic table. Each period corresponds to a new electron shell being filled. Period 1 contains elements whose electrons occupy only the first shell. Period 2 contains elements filling the second shell, and so on. This arrangement means that elements in the same period have electrons in the same number of shells.',
'Elements in the same group or column of the periodic table have the same number of valence electrons and consequently similar chemical properties. Group 1 elements, called alkali metals, all have one valence electron and are highly reactive metals that react vigorously with water. Group 7 elements, called halogens, all have seven valence electrons and are reactive non-metals. Group 0 or Group 18 elements, the noble gases, have completely filled outer shells with either 2 electrons for helium or 8 electrons for the rest, making them extremely unreactive.',
'The periodic table is divided into metals, non-metals, and metalloids. Metals occupy the left and center of the table and make up about 75 percent of all elements. They are typically shiny, good conductors of heat and electricity, malleable, and ductile. Non-metals are found on the right side of the table and generally have opposite properties to metals — they are poor conductors, brittle in solid form, and have lower melting points. Metalloids or semi-metals such as silicon and germanium have properties intermediate between metals and non-metals and are particularly important in semiconductor technology.',
'Trends in properties across periods and down groups can be explained by changes in electronic configuration. Across a period from left to right, the atomic radius generally decreases because more protons are added to the nucleus while electrons are added to the same shell, pulling all electrons closer. Down a group, atomic radius increases because each successive element has an additional electron shell. Ionization energy, which is the energy needed to remove an electron from an atom, generally increases across a period and decreases down a group. These trends make the periodic table a powerful predictive tool for understanding and comparing the properties of elements.'
);

-- =====================================================
-- CHAPTER 3: STATES OF MATTER (5 topics: 3.1 - 3.5)
-- =====================================================

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'3.1', 3, 'The Three States of Matter', 'animation',
'Matter exists in three common states: solid, liquid, and gas. These states differ in the arrangement, movement, and energy of the particles they contain. In a solid, particles are tightly packed together in a regular, ordered arrangement. The particles vibrate about fixed positions but cannot move freely from place to place. This gives solids a definite shape and a definite volume. Solids are generally incompressible because the particles are already as close together as they can be.',
'In a liquid, particles are close together but not in a fixed arrangement. The particles can move past each other, which allows liquids to flow and take the shape of their container. However, the particles in a liquid are still close enough together that liquids have a definite volume and are nearly incompressible. The forces between particles in a liquid are strong enough to keep them from flying apart but not strong enough to hold them in fixed positions. This intermediate state gives liquids their unique flowing properties.',
'In a gas, particles are spread far apart with large spaces between them. Gas particles move rapidly and randomly in all directions, frequently colliding with each other and with the walls of their container. Gases have neither a definite shape nor a definite volume — they expand to fill whatever container they are placed in. Gases are highly compressible because of the large spaces between particles. The particles in a gas have much higher kinetic energy than in solids or liquids, which is why gases exert pressure on the walls of their containers.',
'The kinetic particle theory explains the properties of the three states of matter. According to this theory, all matter is made up of tiny particles that are in constant motion. The higher the temperature, the greater the kinetic energy of the particles and the faster they move. The state of a substance depends on the balance between the kinetic energy of its particles and the strength of the forces between those particles. When kinetic energy overcomes intermolecular forces, a substance changes from solid to liquid to gas. This theory successfully explains properties like diffusion, pressure, and changes of state.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'3.2', 3, 'Changes of State', 'animation',
'A change of state is a physical change in which a substance transforms from one state of matter to another. The six changes of state are melting, freezing, evaporation, condensation, sublimation, and deposition. Melting is the change from solid to liquid, occurring when a solid is heated to its melting point. Freezing is the reverse process — the change from liquid to solid when a liquid is cooled. These two processes occur at the same temperature for a given substance, which is called both the melting point and the freezing point.',
'Evaporation and boiling are both processes by which a liquid changes to a gas, but they differ in important ways. Evaporation occurs at the surface of a liquid at any temperature below the boiling point, as some particles near the surface have enough energy to escape into the gas phase. Boiling occurs throughout the entire liquid when its temperature reaches the boiling point and bubbles of vapor form throughout. Condensation is the reverse of evaporation — the change from gas to liquid when a gas is cooled. Sublimation is the direct change from solid to gas without passing through the liquid state, as seen with dry ice which is solid carbon dioxide.',
'Energy is involved in all changes of state. When a substance melts or evaporates, energy must be supplied to overcome the forces between particles. This energy is called latent heat and it does not change the temperature of the substance — instead it all goes into breaking intermolecular forces. This is why the temperature of melting ice remains at 0°C until all the ice has melted. When a substance freezes or condenses, this same energy is released back to the surroundings. The specific latent heat of fusion is the energy needed to melt one kilogram of a substance at its melting point without changing its temperature.',
'The melting point and boiling point of a substance are characteristic physical properties that can be used to identify it and assess its purity. A pure substance has a sharp, well-defined melting point, while an impure substance melts over a range of temperatures. The presence of dissolved impurities lowers the melting point and raises the boiling point of a substance — this is called freezing point depression and boiling point elevation respectively. These colligative properties depend only on the number of dissolved particles, not on their chemical identity, and have practical applications such as adding salt to roads in winter to prevent ice formation.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'3.3', 3, 'Diffusion', 'animation',
'Diffusion is the net movement of particles from a region of higher concentration to a region of lower concentration, down a concentration gradient. This process occurs as a result of the random motion of particles and requires no energy input — it happens spontaneously. Diffusion continues until the particles are evenly distributed throughout the available space, at which point the concentration is uniform everywhere and a state of dynamic equilibrium is reached. At equilibrium, particles continue to move randomly, but there is no net movement in any direction.',
'Diffusion occurs in both gases and liquids but is much faster in gases because gas particles move more rapidly and have more space between them. The rate of diffusion in gases is demonstrated by the experiment where ammonia gas and hydrogen chloride gas are released simultaneously from opposite ends of a glass tube. A white ring of ammonium chloride forms in the tube where the two gases meet. The ring forms closer to the hydrogen chloride end because ammonia molecules, being lighter, diffuse faster. This demonstrates that lighter molecules diffuse more quickly, as described by Graham''s law of diffusion.',
'Several factors affect the rate of diffusion. Temperature has a significant effect — higher temperatures give particles more kinetic energy, causing them to move faster and diffuse more quickly. The molecular mass of the diffusing substance also affects the rate — lighter molecules move faster and diffuse more quickly than heavier molecules at the same temperature. The concentration gradient affects the rate as well — a steeper gradient means faster net diffusion. In liquids, the viscosity of the liquid affects how quickly particles can move through it, with less viscous liquids allowing faster diffusion.',
'Diffusion is essential to many biological and industrial processes. In the human body, oxygen diffuses from the air in the lungs into the blood, and carbon dioxide diffuses in the opposite direction. Nutrients diffuse from the blood into body cells, while waste products diffuse out. In plants, carbon dioxide diffuses into leaves through tiny pores called stomata for use in photosynthesis. In industrial processes, diffusion is important in dialysis, where waste products diffuse from the blood through a semi-permeable membrane during kidney dialysis treatment. Understanding diffusion is therefore fundamental to both biology and chemistry.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'3.4', 3, 'Gas Laws', 'animation',
'The gas laws describe the mathematical relationships between the pressure, volume, and temperature of a fixed amount of gas. Boyle''s Law states that at constant temperature, the pressure of a fixed mass of gas is inversely proportional to its volume. This means that if the volume of a gas is halved, its pressure doubles, and vice versa. Mathematically, pressure times volume equals a constant, or P₁V₁ equals P₂V₂. This law can be explained using particle theory — if the volume decreases, the particles hit the walls more frequently, increasing the pressure.',
'Charles''s Law states that at constant pressure, the volume of a fixed mass of gas is directly proportional to its absolute temperature measured in Kelvin. This means that if the temperature doubles, the volume also doubles. Mathematically, volume divided by temperature equals a constant, or V₁ divided by T₁ equals V₂ divided by T₂. It is important to use the Kelvin temperature scale, where 0 Kelvin is absolute zero, the theoretical point at which all particle motion stops. To convert from Celsius to Kelvin, add 273 to the Celsius temperature.',
'The Pressure Law states that at constant volume, the pressure of a fixed mass of gas is directly proportional to its absolute temperature in Kelvin. If the temperature increases, the particles move faster, hit the walls harder and more frequently, and the pressure increases. Combining all three gas laws gives the Combined Gas Law: P₁V₁ divided by T₁ equals P₂V₂ divided by T₂. This equation allows the calculation of a new pressure, volume, or temperature when any two of these variables change simultaneously, making it very useful for solving gas law problems.',
'The Ideal Gas Law combines the gas laws with the amount of gas in moles. It states that pressure times volume equals the number of moles times the gas constant R times the absolute temperature, written as PV equals nRT. This equation applies to ideal gases — theoretical gases whose particles have no volume and no intermolecular forces. Real gases behave most like ideal gases at low pressures and high temperatures, where the particles are far apart. The gas laws have many practical applications, including the design of engines, refrigeration systems, and the understanding of atmospheric pressure and weather patterns.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'3.5', 3, 'Intermolecular Forces', 'diagram',
'Intermolecular forces are the forces of attraction that exist between molecules. They are distinct from intramolecular forces, which are the bonds within molecules such as covalent bonds. Intermolecular forces are generally much weaker than covalent or ionic bonds, but they play a crucial role in determining the physical properties of substances such as melting points, boiling points, and solubility. The three main types of intermolecular forces in order of increasing strength are London dispersion forces, dipole-dipole forces, and hydrogen bonding.',
'London dispersion forces, also called van der Waals forces, are the weakest type of intermolecular force and exist between all molecules, whether polar or non-polar. They arise from temporary, instantaneous dipoles that form when the electron cloud of a molecule becomes momentarily unevenly distributed. This temporary dipole induces a dipole in neighboring molecules, creating a weak attractive force. London forces increase with increasing molecular size because larger molecules have more electrons, making larger and more easily polarized electron clouds. This explains why larger non-polar molecules like iodine have higher boiling points than smaller ones like hydrogen.',
'Dipole-dipole forces are attractions between polar molecules that have permanent dipole moments. The partially positive end of one polar molecule is attracted to the partially negative end of a neighboring polar molecule. These forces are stronger than London dispersion forces but weaker than hydrogen bonds. Polar molecules like hydrogen chloride HCl and sulfur dioxide SO₂ experience dipole-dipole forces. The strength of dipole-dipole forces increases with the magnitude of the dipole moment — more polar molecules experience stronger dipole-dipole interactions and consequently have higher boiling points than less polar molecules of similar size.',
'The relative strength of intermolecular forces has a direct impact on the physical properties of substances. Substances with only London dispersion forces, such as non-polar molecules and noble gases, tend to have low boiling points and exist as gases at room temperature unless the molecules are large. Substances with dipole-dipole forces have higher boiling points. Substances with hydrogen bonding have unusually high boiling points relative to their molecular mass, explaining why water has a boiling point of 100°C despite being a small molecule. The type and strength of intermolecular forces also affects viscosity, surface tension, and miscibility of liquids.'
);

-- =====================================================
-- CHAPTER 4: CHEMICAL REACTIONS (6 topics: 4.1 - 4.6)
-- =====================================================

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4, paragraph_5) VALUES (
'4.1', 4, 'Types of Chemical Reactions', 'animation',
'Chemical reactions can be classified into several main types based on the changes that occur. A synthesis or combination reaction is one in which two or more reactants combine to form a single product. For example, iron and sulfur react when heated to form iron sulfide. A decomposition reaction is the opposite — a single compound breaks down into two or more simpler substances. For example, calcium carbonate decomposes on heating to form calcium oxide and carbon dioxide. These two reaction types are essentially reverse processes of each other.',
'A displacement or substitution reaction occurs when a more reactive element displaces or pushes out a less reactive element from its compound. Single displacement reactions involve one element displacing another from a compound. For example, zinc displaces copper from copper sulfate solution because zinc is more reactive than copper. Double displacement reactions, also called precipitation reactions, involve two compounds exchanging ions to form two new compounds, often with one product being an insoluble precipitate. For example, mixing silver nitrate solution with sodium chloride solution produces a white precipitate of silver chloride.',
'Oxidation and reduction reactions, collectively called redox reactions, are extremely important in chemistry. Oxidation was originally defined as the gain of oxygen or loss of hydrogen, while reduction was the loss of oxygen or gain of hydrogen. The modern definition is broader: oxidation is the loss of electrons and reduction is the gain of electrons. These two processes always occur simultaneously — when one substance is oxidized, another is reduced. A useful memory aid is OIL RIG, which stands for Oxidation Is Loss of electrons, Reduction Is Gain of electrons.',
'Reversible reactions are reactions that can proceed in both the forward and reverse directions. They are indicated by a double arrow in chemical equations. When a reversible reaction occurs in a closed system, the rates of the forward and reverse reactions eventually become equal, and the concentrations of reactants and products remain constant. This state is called dynamic equilibrium. Le Chatelier''s Principle states that if a system at equilibrium is subjected to a change in conditions such as temperature, pressure, or concentration, the system will shift to oppose that change and re-establish equilibrium.',
'Neutralization reactions occur when an acid reacts with a base to form a salt and water. This is one of the most important reaction types in chemistry and has numerous practical applications. The general equation for a neutralization reaction is acid plus base produces salt plus water. For example, hydrochloric acid reacting with sodium hydroxide produces sodium chloride and water. Combustion reactions involve the rapid reaction of a substance with oxygen to produce heat and light. Complete combustion of a hydrocarbon produces carbon dioxide and water, while incomplete combustion can produce carbon monoxide or carbon particles, which are harmful pollutants.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'4.2', 4, 'Energy Changes in Reactions', 'animation',
'All chemical reactions involve energy changes. In most reactions, energy is transferred between the reacting chemicals and their surroundings in the form of heat. An exothermic reaction is one that releases heat energy to the surroundings, causing the temperature of the surroundings to increase. Examples of exothermic reactions include combustion, neutralization, and many oxidation reactions. In exothermic reactions, the products have less energy than the reactants, and the difference in energy is released to the surroundings. The energy change is represented by a negative value of enthalpy change, written as a negative delta H.',
'An endothermic reaction is one that absorbs heat energy from the surroundings, causing the temperature of the surroundings to decrease. Examples include thermal decomposition reactions such as the decomposition of calcium carbonate, the dissolving of ammonium nitrate in water, and photosynthesis. In endothermic reactions, the products have more energy than the reactants, and the extra energy is absorbed from the surroundings. The energy change is represented by a positive value of enthalpy change. Everyday applications of endothermic reactions include cold packs used for sports injuries, which feel cold because they absorb heat from the skin.',
'Energy level diagrams, also called reaction profile diagrams, are used to represent the energy changes in chemical reactions. In an exothermic reaction, the products are drawn at a lower energy level than the reactants, and the difference in height represents the energy released. In an endothermic reaction, the products are drawn at a higher energy level than the reactants. All reaction profiles show a peak called the activation energy — this is the minimum energy that reacting particles must have before they can react successfully. A catalyst lowers the activation energy, providing an alternative reaction pathway with a lower energy barrier.',
'Bond breaking and bond forming are the underlying processes responsible for energy changes in reactions. Breaking chemical bonds always requires energy input and is endothermic. Forming chemical bonds always releases energy and is exothermic. In a reaction, bonds in the reactants are broken and new bonds are formed in the products. If more energy is released in forming the new bonds than was needed to break the old bonds, the overall reaction is exothermic. If more energy is required to break bonds than is released in forming new bonds, the overall reaction is endothermic. This bond energy approach allows the enthalpy change of a reaction to be estimated from bond energy data.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4, paragraph_5) VALUES (
'4.3', 4, 'Rate of Reaction', 'animation',
'The rate of a chemical reaction is a measure of how fast reactants are converted into products. It can be defined as the change in concentration of a reactant or product per unit time. Reactions can occur at vastly different rates — some reactions like explosions happen in microseconds, while others like the rusting of iron take years. The rate of a reaction is determined by how frequently reactant particles collide with sufficient energy and in the correct orientation to react. This is the basis of collision theory, which explains why and how reaction rates change.',
'Concentration is one of the main factors affecting the rate of a reaction. Increasing the concentration of reactants in solution increases the number of particles per unit volume, which increases the frequency of collisions between reactant particles. More frequent collisions lead to a higher rate of reaction. For reactions involving gases, increasing the pressure has a similar effect — it decreases the volume, effectively increasing the concentration of gas molecules and leading to more frequent collisions. The relationship between concentration and rate is described by the rate law or rate equation for a specific reaction.',
'Temperature has a dramatic effect on reaction rate. Increasing the temperature increases the kinetic energy of the particles, causing them to move faster and collide more frequently. More importantly, a higher temperature means more particles have energy equal to or greater than the activation energy. Even a small increase in temperature significantly increases the fraction of particles with sufficient energy to react. As a general rule, a 10°C rise in temperature approximately doubles the rate of many reactions. This relationship between temperature and reaction rate has important implications for industrial processes and for understanding biological enzyme activity.',
'Surface area plays an important role in the rate of reactions involving solids. When a solid reactant is broken into smaller pieces or ground into a powder, its surface area increases dramatically. Since reactions can only occur when particles come into contact with the surface of a solid, a larger surface area means more reactant particles are exposed and available for collision. This is why powdered calcium carbonate reacts much more rapidly with hydrochloric acid than marble chips of the same mass. This principle explains why flour dust in grain silos can be explosively reactive despite flour being completely non-explosive in bulk.',
'Catalysts are substances that increase the rate of a chemical reaction without being used up in the process. They work by providing an alternative reaction pathway with a lower activation energy, allowing more particles to have sufficient energy to react successfully. Because catalysts are not consumed in the reaction, a small amount can catalyze the conversion of large amounts of reactants into products. Catalysts are divided into homogeneous catalysts, which are in the same phase as the reactants, and heterogeneous catalysts, which are in a different phase. Industrial examples include iron catalyst in the Haber process for ammonia synthesis and platinum catalyst in catalytic converters.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'4.4', 4, 'Oxidation and Reduction', 'animation',
'Oxidation and reduction are complementary processes that always occur together in what are called redox reactions. The traditional definition describes oxidation as the gain of oxygen or loss of hydrogen, and reduction as the loss of oxygen or gain of hydrogen. For example, when magnesium burns in oxygen, the magnesium is oxidized because it gains oxygen to form magnesium oxide. When copper oxide is heated with hydrogen, the copper oxide is reduced because it loses oxygen to form copper metal, while the hydrogen is simultaneously oxidized to water.',
'The electron transfer definition provides a more comprehensive understanding of redox reactions. Oxidation is defined as the loss of electrons, and reduction is defined as the gain of electrons. These two processes always occur simultaneously — the electrons lost by one substance must be gained by another. The substance that loses electrons is called the reducing agent because it causes the other substance to be reduced by donating electrons to it. The substance that gains electrons is called the oxidizing agent because it causes the other substance to be oxidized by accepting electrons from it.',
'Oxidation numbers, also called oxidation states, provide a way to track electron transfer in redox reactions. The oxidation number represents the charge an atom would have if the bonding electrons were assigned to the more electronegative atom. Rules for assigning oxidation numbers include: the oxidation number of a pure element is zero; the oxidation number of a monoatomic ion equals its charge; oxygen usually has an oxidation number of minus two; hydrogen usually has an oxidation number of plus one. In a redox reaction, the substance being oxidized shows an increase in oxidation number, while the substance being reduced shows a decrease.',
'Electrochemistry provides a practical application of redox chemistry. In electrolysis, an electric current is passed through a molten or dissolved ionic compound to cause a non-spontaneous redox reaction. At the cathode which is the negative electrode, reduction occurs as positive ions gain electrons. At the anode which is the positive electrode, oxidation occurs as negative ions lose electrons. Electrolysis is used industrially to extract reactive metals like aluminum from their ores, to purify copper, and to electroplate metals. The reactivity series of metals is directly related to their tendency to be oxidized, with more reactive metals being more easily oxidized.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'4.5', 4, 'Electrolysis', 'animation',
'Electrolysis is the process of decomposing an ionic compound by passing an electric current through it when it is either molten or dissolved in water. The compound being electrolyzed is called the electrolyte, and it must contain mobile ions that can carry the electric current. In the solid state, ionic compounds cannot conduct electricity because their ions are in fixed positions. However, when melted or dissolved, the ions become free to move and can migrate toward the oppositely charged electrodes. The two electrodes are the cathode which is connected to the negative terminal of the power supply and the anode which is connected to the positive terminal.',
'During electrolysis, positive ions called cations migrate toward the negative cathode and negative ions called anions migrate toward the positive anode. At the cathode, cations gain electrons in a reduction reaction to form neutral atoms or molecules. At the anode, anions lose electrons in an oxidation reaction to form neutral atoms or molecules. The products of electrolysis depend on the electrolyte being used and the electrode material. For example, when molten lead bromide is electrolyzed, lead metal is deposited at the cathode and bromine gas is released at the anode.',
'When aqueous solutions are electrolyzed rather than molten salts, the presence of water complicates the products because water itself can be oxidized or reduced. In the electrolysis of dilute sulfuric acid, hydrogen gas is produced at the cathode as hydrogen ions from water are reduced, and oxygen gas is produced at the anode as water molecules are oxidized. In the electrolysis of concentrated sodium chloride solution called brine, hydrogen gas is produced at the cathode, chlorine gas is produced at the anode, and sodium hydroxide solution remains in the electrolyte. This chlor-alkali process is extremely important industrially.',
'Electrolysis has numerous important industrial applications. Aluminum is extracted from molten aluminum oxide by electrolysis because aluminum is too reactive to be extracted by reduction with carbon. Copper is purified by electrolysis using a pure copper cathode and an impure copper anode in copper sulfate solution — copper dissolves from the anode and pure copper deposits on the cathode. Electroplating uses electrolysis to coat objects with a thin layer of metal for decorative purposes or to prevent corrosion. For example, steel cutlery is often silver-plated or chromium-plated using electrolysis. The quantity of product formed during electrolysis is governed by Faraday''s laws of electrolysis.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'4.6', 4, 'Chemical Equilibrium', 'animation',
'Chemical equilibrium is a state reached in a reversible reaction when the rate of the forward reaction equals the rate of the reverse reaction. At this point, the concentrations of reactants and products remain constant over time, but the reaction has not stopped — it is a dynamic equilibrium where both forward and reverse reactions continue to occur at equal rates. Equilibrium can only be reached in a closed system where reactants and products cannot escape. The position of equilibrium describes whether the equilibrium mixture contains more reactants or more products at equilibrium.',
'Le Chatelier''s Principle is a fundamental principle used to predict how a system at equilibrium responds to changes in conditions. It states that if a change is made to a system at equilibrium, the system will shift in the direction that opposes that change. If the concentration of a reactant is increased, the equilibrium shifts to the right to use up some of the added reactant and produce more products. If the concentration of a product is increased, the equilibrium shifts to the left. Removing a reactant or product has the opposite effect. A catalyst does not shift the position of equilibrium — it only helps the system reach equilibrium faster.',
'Temperature changes affect equilibrium position by favoring either the forward or reverse reaction depending on whether the reaction is exothermic or endothermic. For an exothermic reaction, increasing the temperature shifts the equilibrium to the left, favoring the reverse endothermic reaction and reducing the yield of products. Decreasing the temperature shifts the equilibrium to the right, increasing the yield. For an endothermic reaction, the opposite applies. Pressure changes affect equilibrium in reactions involving gases — increasing pressure favors the side with fewer moles of gas, shifting the equilibrium toward fewer gas molecules.',
'The Haber process for manufacturing ammonia is an important industrial application of equilibrium principles. Nitrogen and hydrogen gases react reversibly to form ammonia in an exothermic reaction. To maximize ammonia yield, low temperature and high pressure would be favored by Le Chatelier''s Principle. However, low temperature makes the reaction too slow, so a compromise temperature of around 450°C is used with an iron catalyst to achieve an acceptable rate. High pressure of around 200 atmospheres is used to shift equilibrium toward ammonia. The ammonia is continuously removed from the equilibrium mixture, which causes the equilibrium to shift right to produce more ammonia, further improving yield.'
);

-- =====================================================
-- CHAPTER 5: ACIDS, BASES AND SALTS (5 topics: 5.1 - 5.5)
-- =====================================================

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'5.1', 5, 'Acids and Their Properties', 'animation',
'An acid is a substance that produces hydrogen ions H⁺ when dissolved in water. More precisely, acids donate protons which are hydrogen ions to other substances — this is the Brønsted-Lowry definition of an acid. Common laboratory acids include hydrochloric acid HCl, sulfuric acid H₂SO₄, and nitric acid HNO₃. These are all strong acids, meaning they fully dissociate in water to produce hydrogen ions. Weak acids such as ethanoic acid CH₃COOH and carbonic acid H₂CO₃ only partially dissociate in water, producing fewer hydrogen ions and thus lower acidity.',
'Acids share a set of characteristic chemical properties that can be used to identify them. Acids have a sour taste, though tasting laboratory chemicals is extremely dangerous and should never be done. Acids turn blue litmus paper red and have a pH below 7. Acids react with metals above hydrogen in the reactivity series to produce a salt and hydrogen gas. For example, zinc reacts with hydrochloric acid to produce zinc chloride and hydrogen. Acids react with metal oxides and metal hydroxides to produce a salt and water only. Acids react with metal carbonates and metal hydrogencarbonates to produce a salt, water, and carbon dioxide gas.',
'The pH scale is a measure of the acidity or alkalinity of a solution. It runs from 0 to 14, with 7 being neutral. Values below 7 indicate acidic solutions, with lower values indicating stronger acids — a solution of pH 1 is more acidic than a solution of pH 5. Values above 7 indicate alkaline solutions, with higher values indicating stronger alkalis. The pH scale is logarithmic, meaning each unit change in pH represents a tenfold change in hydrogen ion concentration. pH is measured using indicators, pH paper, or a pH meter. Universal indicator changes through a range of colors corresponding to different pH values.',
'The concentration of an acid affects its reactivity. Concentrated acids have a higher number of acid molecules per unit volume and react more vigorously than dilute acids. The strength of an acid is different from its concentration — strength refers to the degree of dissociation, while concentration refers to the amount of acid dissolved per unit volume. A concentrated weak acid can be less reactive than a dilute strong acid. Strong acids are completely ionized in solution, while weak acids reach an equilibrium between ionized and un-ionized forms. This distinction is important in understanding the behavior of acids in chemical reactions and in biological systems.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'5.2', 5, 'Bases and Alkalis', 'diagram',
'A base is a substance that can accept a proton from an acid, or in simpler terms, a substance that neutralizes an acid to form a salt and water only. Metal oxides and metal hydroxides are common examples of bases. An alkali is a special type of base that dissolves in water to produce hydroxide ions OH⁻. All alkalis are bases, but not all bases are alkalis — for example, copper oxide is a base but does not dissolve in water and so is not an alkali. Common alkalis include sodium hydroxide NaOH, potassium hydroxide KOH, calcium hydroxide Ca(OH)₂, and ammonia solution NH₃.',
'Alkalis share characteristic properties that distinguish them from acids. Alkalis feel soapy or slippery to the touch due to their reaction with oils on the skin, though touching concentrated alkalis is dangerous. Alkalis turn red litmus paper blue and have a pH above 7. Alkalis react with acids in neutralization reactions to form salts and water. Alkalis react with ammonium salts when heated to produce a salt, water, and ammonia gas — this reaction is used as a laboratory test for ammonium ions. Alkalis also react with solutions of metal salts to precipitate metal hydroxides, many of which are colored and can be used to identify metal ions.',
'Strong and weak bases differ in the extent to which they ionize in water. Strong bases like sodium hydroxide and potassium hydroxide are fully ionized in solution, producing a high concentration of hydroxide ions. Weak bases like ammonia solution are only partially ionized, producing fewer hydroxide ions and thus a lower pH. The strength of a base determines its reactivity — strong bases react more vigorously with acids than weak bases of the same concentration. In the Brønsted-Lowry theory, a base is any substance that accepts a proton, which broadens the definition beyond just hydroxide-producing substances.',
'Bases and alkalis have many important practical applications. Sodium hydroxide is used in the manufacture of soap through a process called saponification, where fats and oils react with alkali to produce glycerol and soap molecules. Calcium hydroxide, known as slaked lime, is used in agriculture to neutralize acidic soils and improve crop yields. Magnesium hydroxide and aluminum hydroxide are used in antacid medicines to neutralize excess stomach acid and relieve indigestion. Ammonia solution is used as a cleaning agent. Understanding the properties of bases and alkalis is therefore important not just in chemistry but in everyday applications and industry.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'5.3', 5, 'Neutralization and Salts', 'animation',
'Neutralization is the reaction between an acid and a base to produce a salt and water. The hydrogen ions from the acid react with the hydroxide ions from the base to form water molecules. In ionic terms, the neutralization reaction can be written as H⁺ plus OH⁻ producing H₂O. The other ions present form the salt. The resulting solution is neutral only if the acid and base are present in exactly the right proportions — the equivalence point. Neutralization reactions are exothermic, releasing heat energy, which is why mixing a strong acid with a strong alkali causes a noticeable temperature rise.',
'A salt is an ionic compound formed when the hydrogen ions of an acid are replaced by metal ions or ammonium ions. The name of a salt consists of two parts: the metal or ammonium part from the base and the acid part from the acid. Hydrochloric acid produces chloride salts, sulfuric acid produces sulfate salts, nitric acid produces nitrate salts, and carbonic acid produces carbonate salts. For example, hydrochloric acid reacting with sodium hydroxide produces sodium chloride, commonly known as table salt. Sulfuric acid reacting with copper oxide produces copper sulfate.',
'Salts can be prepared by several different methods depending on the properties of the salt required. Soluble salts are prepared by reacting an acid with an excess of a metal, metal oxide, metal hydroxide, or metal carbonate, then filtering off the excess solid and evaporating the filtrate to crystallize the salt. Insoluble salts are prepared by mixing solutions of two soluble salts that react together to form an insoluble precipitate — this is called a precipitation reaction. For example, lead sulfate can be prepared by mixing lead nitrate solution with sodium sulfate solution. The precipitate is filtered, washed, and dried.',
'Titration is a precise laboratory technique used to determine the exact volume of one solution needed to react completely with a known volume of another solution. In an acid-base titration, a measured volume of acid is placed in a conical flask with an indicator. Alkali is added from a burette drop by drop until the indicator changes color at the end point, showing that neutralization is complete. The volume of alkali used, called the titre, is recorded. By repeating the titration without the indicator, a pure neutral salt solution can be obtained and then crystallized. Titration allows the precise preparation of pure salts and accurate determination of solution concentrations.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'5.4', 5, 'The pH Scale and Indicators', 'diagram',
'The pH scale is a quantitative measure of the acidity or alkalinity of a solution, ranging from 0 to 14 under standard conditions. The scale is based on the concentration of hydrogen ions in solution. A neutral solution, such as pure water at 25°C, has a pH of exactly 7, meaning that the concentration of hydrogen ions equals the concentration of hydroxide ions. Acidic solutions have a pH below 7 because they contain more hydrogen ions than hydroxide ions. Alkaline solutions have a pH above 7 because they contain more hydroxide ions than hydrogen ions.',
'The pH scale is logarithmic, which means each whole number change in pH corresponds to a tenfold change in hydrogen ion concentration. A solution of pH 3 has ten times more hydrogen ions than a solution of pH 4, and one hundred times more hydrogen ions than a solution of pH 5. This logarithmic nature means that even small changes in pH represent large changes in acidity. For example, the pH of human blood is maintained very precisely between 7.35 and 7.45 — a drop to pH 7.0 would be life-threatening. The logarithmic scale allows a very wide range of hydrogen ion concentrations to be expressed as a simple number between 0 and 14.',
'Indicators are substances that change color depending on the pH of the solution they are in. They are used to determine whether a solution is acidic, neutral, or alkaline. Litmus is one of the most common indicators — it turns red in acid and blue in alkali, but does not show the actual pH value. Universal indicator is a mixture of several indicators that shows a range of colors corresponding to different pH values: red and orange for strong and weak acids, green for neutral, and blue and purple for weak and strong alkalis. A pH meter gives a precise digital reading of pH and is more accurate than color indicators.',
'Different indicators are suitable for different purposes in titrations. The choice of indicator depends on the nature of the acid and base being used. Phenolphthalein is colorless in acid and pink in alkali, making it suitable for strong acid-strong base titrations. Methyl orange is red in acid and yellow in alkali and is more suitable when a strong acid is being titrated against a weak base. Using the wrong indicator can give inaccurate results because different indicators change color at different pH values. In acid-base titrations, the indicator should change color sharply at the equivalence point, which is where the acid and base have exactly neutralized each other.'
);

INSERT INTO topics (topic_id, chapter_id, topic_name, visual_type, paragraph_1, paragraph_2, paragraph_3, paragraph_4) VALUES (
'5.5', 5, 'Preparation and Uses of Salts', 'diagram',
'The method used to prepare a salt depends on whether the salt is soluble or insoluble in water, and on the reactivity of the metal involved. For soluble salts that contain a reactive metal such as zinc or iron, the salt can be prepared by reacting the metal directly with a dilute acid. The metal is added in excess to ensure all the acid is used up, then the excess metal is filtered off, and the salt solution is evaporated to produce crystals of the pure salt. For example, zinc sulfate can be prepared by reacting zinc with dilute sulfuric acid.',
'Soluble salts containing metals that do not react with dilute acids, such as copper, are prepared using the metal oxide or metal carbonate instead. Copper sulfate is prepared by reacting excess copper oxide or copper carbonate with dilute sulfuric acid. The excess copper compound is filtered off, and the filtrate is evaporated. Another method for preparing soluble salts is neutralization — an acid is titrated against an alkali using an indicator to find the exact volumes needed for neutralization, then the experiment is repeated without indicator to obtain a pure salt solution, which is then crystallized.',
'Insoluble salts are prepared by precipitation — mixing two solutions that contain the required ions. When the two solutions are mixed, the insoluble salt forms immediately as a precipitate. For example, barium sulfate, which is insoluble, can be prepared by mixing barium chloride solution with sodium sulfate solution. The precipitate is collected by filtration, washed with distilled water to remove any soluble impurities, and then dried. This method is also used in qualitative analysis to identify the presence of specific ions — for example, adding silver nitrate solution to a solution containing chloride ions produces a white precipitate of silver chloride.',
'Salts have enormous importance in industry, agriculture, and everyday life. Sodium chloride is used in the food industry as a preservative and flavoring agent, and is also the raw material for the chlor-alkali industry which produces chlorine, hydrogen, and sodium hydroxide. Ammonium nitrate and ammonium sulfate are widely used as agricultural fertilizers, providing nitrogen to plants. Calcium sulfate, known as gypsum, is used in the construction industry to make plaster. Copper sulfate is used as a fungicide in agriculture and as a blue pigment. Understanding salt preparation and properties is essential to many industrial and agricultural processes.'
);

-- =====================================================
-- VERIFY INSERTION
-- =====================================================
SELECT topic_id, topic_name, visual_type FROM topics ORDER BY topic_id;
SELECT COUNT(*) as total_topics FROM topics;